version: "3"
services:
  dev_db:
    image: "postgres:11"
    container_name: "dev-db"
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=Password123
      - POSTGRES_DB=dev_db
    ports:
      - "54323:5432"
    volumes:
      - ~/dev_db:/var/lib/dev_db
  api-assignment:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-assignment:1.0
    ports:
      - "3000:3000"
    command: bash -c 'while !</dev/tcp/dev_db/5432; do sleep 1; done; npm start'
    links:
      - dev_db
    environment:
#      - DB_CONNECTION_STRING=postgres://dev_user:Password123@dev_db:5432/dev_db
      - DATABASE_HOST=dev_db
      - DATABASE_PORT=5432
      - DATABASE_USER=dev_user
      - DATABASE_NAME=dev_db
      - PORT=3000
    depends_on:
      - dev_db
